// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAJbW6vdZANPLKZMg7V9x3NrXFWs6ohw4',
    appId: '1:49354242108:web:a746d01f94705be5abab39',
    messagingSenderId: '49354242108',
    projectId: 'instagram-flutter-clone98',
    authDomain: 'instagram-flutter-clone98.firebaseapp.com',
    storageBucket: 'instagram-flutter-clone98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzAz0rCH4E6Pjk6bDv-Wdqpx-QxF74eOg',
    appId: '1:49354242108:android:9f07e8786214f620abab39',
    messagingSenderId: '49354242108',
    projectId: 'instagram-flutter-clone98',
    storageBucket: 'instagram-flutter-clone98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIyK03_xER1HTQNFBlHSevfTEyfnuuA-c',
    appId: '1:49354242108:ios:e1a76ccc9b3b9bf6abab39',
    messagingSenderId: '49354242108',
    projectId: 'instagram-flutter-clone98',
    storageBucket: 'instagram-flutter-clone98.appspot.com',
    iosClientId: '49354242108-puqd7egot7u4fja5ktea1ga8158q43pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIyK03_xER1HTQNFBlHSevfTEyfnuuA-c',
    appId: '1:49354242108:ios:a82a9cad52893ee4abab39',
    messagingSenderId: '49354242108',
    projectId: 'instagram-flutter-clone98',
    storageBucket: 'instagram-flutter-clone98.appspot.com',
    iosClientId: '49354242108-3a6ov0luclngvh6ok3gku27s4tsntseh.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutterClone.RunnerTests',
  );
}
